[package]
name = "alws"
version = "0.1.0"
authors = ["john.salamon"]

[dependencies]
petgraph = { version = "0.4.11", features = ["serde-1"] }
chrono = { version = "0.4", features = ["serde", "rustc-serialize"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"